source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'SuperLogger', '~> 0.9'
pod 'AFNetworking', '~> 3.0'
#pod 'VIMNetworking', '~> 6.0'

target 'VimeoVideoUploader' do

end

